"""Initial migration

Revision ID: a07201056567
Revises: 
Create Date: 2023-12-22 14:06:23.666907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07201056567'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Без заказа', 'Выполняет заказ', name='courier_status'), server_default='Без заказа', nullable=False, comment='Статус работы курьера'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.CheckConstraint("phone_number ~ '^((\\+7|7|8)+([0-9]){10})$'", name='check_phone_number'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_index(op.f('ix_couriers_status'), 'couriers', ['status'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False, comment='Время открытия ресторана'),
    sa.Column('closing_time', sa.Time(), nullable=False, comment='Время закрытия ресторана'),
    sa.Column('duration_delivery', sa.Integer(), nullable=False, comment='Примерное время доставки заказа/в минутах'),
    sa.Column('city', sa.String(), server_default='Тюмень', nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), server_default='Тюмень', nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.CheckConstraint("phone_number ~ '^((\\+7|7|8)+([0-9]){10})$'", name='check_phone_number'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Поиск курьера', 'В пути', 'Доставлен', name='delivery_status'), server_default='Поиск курьера', nullable=False, comment='Статус доставки'),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text("date_trunc('second', (now() at time zone 'Asia/Yekaterinburg'))"), nullable=False, comment='Время начала доставки'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Время завершения доставки'),
    sa.Column('restaurant_id', sa.Integer(), nullable=False, comment='ID ресторана'),
    sa.Column('courier_id', sa.Integer(), nullable=True, comment='ID курьера'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_couriers_status'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###
